version: '2'
volumes:
    node-red-data:
    node-red-data2:
    kodi-data: {}
services:
  samba:
    #  hostname: samba  # doesn't work
    image: dastrasmue/rpi-samba 
    command:  -u "jan:passw0rd!67" -s "node-red-data:/mount/node-red-data:rw:jan"  
    volumes:
       - 'node-red-data:/mount/node-red-data'
    ports:
    #  - "137:137"
    #  - "137:137/udp"
      - "139:139"
      - "445:445"
    #  - "445:445/udp"
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  kodi:
    build: kodi
    privileged: true
    restart: always
    #network_mode: host
    volumes:
      - 'kodi-data:/data'
    ports:
      - "8080:8080"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.update.strategy: download-then-kill
      io.balena.update.handover-timeout: ''
  node-red:
    build: node-red
    privileged: true
    volumes:
       - 'node-red-data:/dataX'
       - 'node-red-data2:/data2'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
    labels:
      io.balena.features.kernel-modules: '1'
    environment:
      - TZ=Europe/Brussels
  nginx:
    build : nginx
    depends_on:
      - node-red
      - kodi
    ports:
       - "80:80"
       - "443:443"
    restart: always

