version: '2'
volumes:
    node-red-data:
    influxdb-data:
    kodi-data: {}
services:
  samba:
    #  hostname: samba  # doesn't work
    image: dastrasmue/rpi-samba 
    command:  -u "jan:passw0rd!67" -s "node-red-data:/mount/node-red-data:rw:jan"  
    volumes:
       - 'node-red-data:/mount/node-red-data'
    ports:
    #  - "137:137"
    #  - "137:137/udp"
      - "139:139"
      - "445:445"
    #  - "445:445/udp"
  influxdb:
    build: influxdb
    container_name: influxdb
    # privileged added so usb drive can be mounted.
    privileged: true
    volumes:
        # take care that the mount location "/mnt/influxdb" becomes overwritten
        # by the mount location specified in the influxdb Dockerfile.
        - 'influxdb-data:/mnt/influxdb'   
    ports:
      # The API for InfluxDB is served on port 8086
      - "8082:8082"
      - "8086:8086"
      # UDP Port
      - "8089:8089"
    restart: always
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build : telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    depends_on:
      - influxdb
    restart: always
    environment:
       - interval=60s
       - flush_interval=60s
  grafana:
    build: grafana 
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  kodi:
    build: kodi
    privileged: true
    restart: always
    #network_mode: host
    volumes:
      - 'kodi-data:/data'
    ports:
      - "8080:8080"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.update.strategy: download-then-kill
      io.balena.update.handover-timeout: ''
  node-red:
    build: node-red
    privileged: true
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
    labels:
      io.balena.features.kernel-modules: '1'
    environment:
      - TZ=Europe/Brussels
  nginx:
    build : nginx
    depends_on:
      - grafana
      - node-red
      - kodi
    ports:
       - "80:80"
       - "443:443"
    restart: always

